# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essays',
            fields=[
                ('essay_id', models.AutoField(primary_key=True, serialize=False)),
                ('essay_content', models.TextField()),
                ('groundtruth_score', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('predicted_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('submited_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Essays',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='essays',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Questions'),
        ),
    ]
